---
id: surrey
url: 'http://surrey.ca.granicus.com/ViewPublisher.php?view_id=1'
provider: granicus
youtube:
  title: Surrey {title}, {start_ts:%Y-%m-%d}
  desc: >
    {title} on {start_ts:%A, %B} {start_ts.day}, {start_ts:%Y}.
    Surrey City Council in British Columbia, Canada.
  location: [49.191307, -122.848743]
  location_desc: Surrey City Hall, Surrey, BC, Canada
  playlists:
    - '{start_ts:%Y} Surrey BC City Council Meetings'
    - '{category}'
  tags: [surrey, bc, canada, city council meeting]
  privacy: public
  notify_subscribers: true
audio_mono: true
---
id: poco
url: 'https://portcoquitlam.ca.granicus.com/ViewPublisher.php?view_id=2'
provider: granicus
---
id: burnaby
url: 'http://civic.neulion.com/cityofburnaby/'
provider: neulion
youtube:
  title: Burnaby City Council Meeting, {start_ts:%Y-%m-%d}
  desc:
    Burnaby City Council Meeting on {start_ts:%A, %B} {start_ts.day}, {start_ts:%Y}.


    {timecodes}
  playlists:
    - '{start_ts:%Y} Burnaby BC City Council Meetings'
  tags: [burnaby, bc, canada, city council meeting]
  privacy: public
  notify_subscribers: true
---
id: vancouver
url: 'http://civic.neulion.com/cityofvancouver/'
provider: neulion
youtube:
  title: '{title}, {start_ts:%Y-%m-%d}'
  desc: >
    {category} on {start_ts:%A, %B} {start_ts.day}, {start_ts:%Y}.
    Vancouver City Council in British Columbia, Canada.


    {timecodes}
  location: [49.260832, -123.113962]
  location_desc: Vancouver City Hall, Vancouver, BC, Canada
  playlists:
    - '{start_ts:%Y} Vancouver BC City Council Meetings'
    - '{category}'
  tags: [vancouver, bc, canada, city council meeting]
  privacy: public
  notify_subscribers: true
---
id: coquitlam
url: 'http://coquitlam.insinc.com'
provider: insinc
youtube:
  title: 'Coquitlam {category}, {start_ts:%Y-%m-%d}'
  desc: >
    {category} on {start_ts:%A, %B} {start_ts.day}, {start_ts:%Y}. {title}.
    Coquitlam City Council in British Columbia, Canada.


    {timecodes}
  location: [49.2844794, -122.7931796]
  location_desc: Coquitlam City Hall, Coquitlam, BC, Canada
  playlists:
    - '{start_ts:%Y} Coquitlam BC City Council Meetings'
    - '{category}'
  tags: [coquitlam, bc, canada, city council meeting]
  privacy: unlisted
  notify_subscribers: true
#---
#id: langley
#url: 'http://civic.neulion.com/cityoflangley/'
